# Generated by Django 5.0.6 on 2026-04-24 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='confirmée le'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='confirmée par'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('rejected', 'Rejetée'), ('payment_pending', 'Paiement en cours'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='statut'),
        ),
    ]
