# Generated by Django 6.0.3 on 2026-04-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('space_type', models.CharField(choices=[('desk', 'Bureau individuel'), ('open_space', 'Espace ouvert'), ('meeting_room', 'Salle de réunion'), ('private', 'Bureau privé'), ('conference', 'Salle de conférence')], max_length=20, verbose_name="type d'espace")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='capacité (personnes)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix par heure (FCFA)')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix par jour (FCFA)')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='adresse')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='spaces/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('amenities', models.ManyToManyField(blank=True, related_name='spaces', to='spaces.amenity', verbose_name='équipements')),
            ],
            options={
                'verbose_name': 'Espace',
                'verbose_name_plural': 'Espaces',
                'ordering': ['name'],
            },
        ),
    ]
