# Generated by Django 6.0.3 on 2026-04-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='référence')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='fichier PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
    ]
