# Generated by Django 6.0.3 on 2026-04-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_alter_space_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='spaces/photos/', verbose_name='photo')),
                ('is_primary', models.BooleanField(default=False, verbose_name='photo principale')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploadée le')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spaces.space', verbose_name='espace')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
    ]
