# Generated by Django 6.0.3 on 2026-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_spacephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='photo',
        ),
    ]
