# Generated by Django 6.0.3 on 2026-04-06 14:21

import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_remove_space_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spacephoto',
            options={'ordering': ['-is_primary', 'position', '-uploaded_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='spacephoto',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='position/ordre'),
        ),
        migrations.AlterField(
            model_name='spacephoto',
            name='file',
            field=imagekit.models.fields.ProcessedImageField(upload_to='spaces/photos/', verbose_name='photo'),
        ),
    ]
