# Generated by Django 6.0.3 on 2026-04-01 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reservation_confirmed', 'Réservation confirmée'), ('reservation_cancelled', 'Réservation annulée'), ('reservation_reminder', 'Rappel de réservation'), ('payment_completed', 'Paiement effectué'), ('payment_failed', 'Paiement échoué'), ('payment_refunded', 'Paiement remboursé')], max_length=30, verbose_name='type de notification')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10, verbose_name="canal d'envoi")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyée'), ('failed', 'Échouée')], default='pending', max_length=10, verbose_name='statut')),
                ('message', models.TextField(verbose_name='message')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reservations.reservation', verbose_name='réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
