# Generated by Django 5.0.6 on 2026-04-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_received', 'Demande reçue'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_rejected', 'Réservation rejetée'), ('reservation_cancelled', 'Réservation annulée'), ('reservation_reminder', 'Rappel de réservation'), ('payment_completed', 'Paiement effectué'), ('payment_failed', 'Paiement échoué'), ('payment_refunded', 'Paiement remboursé')], max_length=30, verbose_name='type de notification'),
        ),
    ]
