# Generated by Django 5.0.6 on 2026-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='lue'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_received', 'Demande reçue'), ('reservation_request', 'Nouvelle demande (admin)'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_rejected', 'Réservation rejetée'), ('reservation_cancelled', 'Réservation annulée'), ('reservation_reminder', 'Rappel de réservation'), ('payment_completed', 'Paiement effectué'), ('payment_received', 'Paiement reçu (admin)'), ('payment_failed', 'Paiement échoué'), ('payment_refunded', 'Paiement remboursé')], max_length=30, verbose_name='type de notification'),
        ),
    ]
