# Generated by Django 6.0.3 on 2026-04-01 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='date et heure de début')),
                ('end_datetime', models.DateTimeField(verbose_name='date et heure de fin')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('rejected', 'Rejetée')], default='pending', max_length=20, verbose_name='statut')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix total (FCFA)')),
                ('billing_type', models.CharField(choices=[('hourly', 'Par heure'), ('daily', 'Par jour')], default='hourly', max_length=10, verbose_name='type de facturation')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='récurrente')),
                ('recurrence_rule', models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='none', max_length=10, verbose_name='règle de récurrence')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifiée le')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='spaces.space', verbose_name='espace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
